---
- hosts: localhost
  tasks:
    - pip:
        name: boto 
    - name: Create AWS EC2 Instances
      ec2:
        key_name: asajid-aws
        instance_type: t2.micro
        image: ami-0b0dcb5067f052a63
        wait: yes
        group: default
        count: 2
        region: us-east-1
      register: ec2
