---

- hosts: all
  become: true
  tasks:

  - name: install updates (amazon linux 2)
    yum:
      update_only: yes
      update_cache: yes


  - name: install docker add php support for apache install httpd
    yum: 
      name: 
        - docker
        - httpd
        - php  
      state: latest 
   
  - name: update repository index
    yum:
      update_cache: yes

  - name: uninstall tree
    yum: 
      name: 
        - tree
      state: absent      

  - name: install ldap package
    yum:
      name: ldap
      state: latest
   
  - name: check ldap service status
    service:
      name: ldap
      status: started    

  - name: install tree 
    yum:
      name: 
        - tree
      state: installed
   
  - name: mkdir -p  love,run,goof run tree command on love
    service:
      name: 
        - mkdir -p
        - tree   

